### ISSUE TITLE
Model extension: Narrative sign restriction 

### ISSUE THREAD

**Issue by mantihuang** [mantihuang/research_project#4]
Hi @donotdespair,

In light of our converstation, I am considering the narrative sign restriction , as proposed in an AER paper by Antolín-Díaz and Rubio-Ramírez (2018), as an extension to the baseline model.

I am are considering the following two particular time periods for restrictions on the signs of government spending shocks:

1. The COVID-19 pandemic
2. The financial crisis of 2007-2008

I plan to conduct research to determine if there is a consensus on the sign of government spending shocks during these periods. Any suggestions or guidance would be highly valued. 

Thank you for your help ~~

DON'T DESPAIR!

Best,
Manting

**Comment by donotdespair** [comment]
Hi @mantihuang 

Fantastic!! Let's take it from here and get in touch as the project progresses (and let's not despair!) It seems you have enough info to begin with.

Cheers,

@donotdespair

**Comment by donotdespair** [comment]
@mantihuang 

The working paper on Covid-specific heteroskedasticity by Lenza & Primiceri is [How to Estimate a VAR after March 2020](https://www.nber.org/papers/w27771)

**Comment by mantihuang** [comment]
Hi @donotdespair ,

I am wondering if the narrative sign restriction is the same as restriction the IRF for a specific period.

Thanks

**Comment by donotdespair** [comment]
Hi @mantihuang 

Well, no, it isn't! Restrictions on IRFs restrict the response, the restrictions on the shock restrict the shock! But they have to be aligned. If you assume a positive response to the shock then this determines the sign of the restriction on the shock itself. Does this help?

**Comment by mantihuang** [comment]
Hi @donotdespair 

Thank you very much for your reply. After the loop for sign restriction is completed, there is another restriction on the the specific period draws of B0.


Thanks you for your help.

Best,
Manting

**Comment by donotdespair** [comment]
Hi @mantihuang 

Here's the reference to the sign and zero restrictions paper by [Ariaz, Rubio-Ramirez, Waggoner](https://onlinelibrary.wiley.com/doi/abs/10.3982/ECTA14468)

Good luck! @donotdespair

**Comment by mantihuang** [comment]
Hi @donotdespair ,

I've committed 7923bc3aec5b7b2c5e420910a6bc59d2bda725c2 a portion of my empirical results, but I find the plot of the impulse response function to be unusual. Could you kindly assist me in examining it? I also describe sign restriction in the website.  

Thank you very much !

@mantihuang

**Comment by donotdespair** [comment]
Hi @mantihuang 

OK, They're OK! The point is about how to conceptualise the changes... It's a bit difficult as ATM you don't report the plot of the conditional standard deviations. Also the trace plots of $A_{38}$ reveals that convergence takes some more draws, so please make certain that you only use MCMC sample after convergence. The shapes of the IRFs are OK also for heteroskedastic model. My guess is that they experess much stronger shrinkage of $A$ towards the prior mean (random walk) due to the estimation of a latent variable (the time-varying variances) that overburdens the data, not providing essential improvements (for your data specifically).

How does this sound to you?

Greetings, T

**Comment by mantihuang** [comment]
Hi @donotdespair ,

Thank you very much for your suggestion. I'll add the plot of the standard deviations later today and try to conceptualize the changes.

Thank you again.

Best,
Manting
