### ISSUE TITLE
Model Extension: Hyperparameters

### ISSUE THREAD

**Issue by mantihuang** [mantihuang/research_project#8]
Hello @donotdespair,

In this extension, I would like to delve further into the kappa parameter for matrix A.

$$K_A \sim \text{{Gamma}}(\underline{s}, 1/2 )$$

Here,  $\underline{s}$ represents the scale parameter, and $1/2$ corresponds to the shape parameter.

It would be really helpful if you could provide me with related literature on this topic. 

https://cran.r-project.org/web/packages/GIGrvg/GIGrvg.pdf

Thank you 

@mantihuang

**Comment by donotdespair** [comment]
Hi @mantihuang 

OK, great! Let's begin with a small correction your prior can be written as in your equation, but the $\underline{s}$ parameter is the **scale** and the $1/2% is the **shape**, so the prior mean of $\kappa_A$ is equal to $0.5*\underline{s}$. This parameterization and naming are in line with the [Wikipedia entry](https://en.wikipedia.org/wiki/Gamma_distribution) and the R function `rgamma`. 

Your essential resource is the **GIGrvn** package that will allow your estimation using its function `rgig` that samples random draws from the generalised inverse Gaussian distribution that will be your full conditional posterior for this hyper-parameter. Just type `?GIGrvn::rgig` in R to see the kernel of this distribution.

The most relevant paper introducing this type of priors is the one by [Griffin and Brown](https://projecteuclid.org/journals/bayesian-analysis/volume-12/issue-1/Hierarchical-Shrinkage-Priors-for-Regression-Models/10.1214/15-BA990.full) and [these fellows (fantastic statisticians and econometricians)](https://www.mdpi.com/2225-1146/8/2/20) show how far this type of hierarchical modelling can go.

Good luck! @donotdespair

**Comment by mantihuang** [comment]
Hi @donotdespair ,
I have derived the posterior distribution for $\kappa_A$. Can you please review its correctness?

Now assume that 

$$A|\Sigma \sim MN_{K \times N} (\underline{A}, \Sigma , \underline{\kappa}_A \underline{V}) $$

where : 

$$\kappa_A \sim G(\underline{s}_A,\frac{1}{2})$$.

Then the posterior of $\kappa_A$ is calculated as follows:

$$P(\kappa_A |Y,X,A) = L(Y|X,A,\Sigma) \times P(\kappa_A) \times P(A|\Sigma,\kappa_A) \times P(\Sigma)  \\ \propto p(\kappa_A) \times P(A|\Sigma,\kappa_A) \\ 
= \kappa_A^{\frac{1}{2}-1} exp\{ {-\frac{\kappa_A}{\underline{s}_A}}\} \times
det(\kappa_A \underline{V})^{-\frac{N}{2}} \times exp \{-\frac{1}{2} tr[\Sigma ^{-1} (A - \underline{A})' (\kappa_A \underline{V})^{-1}] (A - \underline{A}) \} \\
= \kappa_A ^{\frac{1}{2} - \frac{N}{2} - 1} \times exp \{-\frac{1}{2} [\frac{1}{\kappa_A}tr \Sigma^{-1}(A - \underline{A})'(\underline{V}^{-1})(A - \underline{A})] + \frac{2}{s_A}\kappa_A \}$$

which it is the kernel of Generalized Inverse Gaussian (GIG) distribution with 

$$\lambda = \frac{1}{2} - \frac{N}{2} $$ 

$$\chi = tr (\Sigma^{-1}(A - \underline{A})'(\underline{V}^{-1})(A - \underline{A})) $$

$$\psi = \frac{2}{s_A}$$

Thank you very much~

**Comment by donotdespair** [comment]
Hi @mantihuang ,

All seems ok but you lost 'K' in 'lambda':

$$\lambda = \frac{1}{2} - \frac{KN}{2} $$

Is this right?

**Comment by mantihuang** [comment]
hi @donotdespair ,

I think it is just N since A is matrix-variate normal distribution and the constant of density function is 

$$ (2\pi)^\frac{KN}{2}det(\Sigma)^{\frac{K}{2} } det(\kappa_A \underline{V})^{\frac{N}{2}}$$

Please correct me if I am wrong~

Thank you 

Best,
Manting

**Comment by donotdespair** [comment]
Yep @mantihuang  work or the 'det' formula

**Comment by mantihuang** [comment]
Hi @donotdespair 

Thanks !! You are right. $ \underline{V}$ is k by k.
